package com.backport;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.sounds.SoundEvent;

public final class BackportSounds {
   public static final SoundEvent BLOCK_COPPER_BULB_BREAK = register("block.copper_bulb.break");
   public static final SoundEvent BLOCK_COPPER_BULB_FALL = register("block.copper_bulb.fall");
   public static final SoundEvent BLOCK_COPPER_BULB_HIT = register("block.copper_bulb.hit");
   public static final SoundEvent BLOCK_COPPER_BULB_PLACE = register("block.copper_bulb.place");
   public static final SoundEvent BLOCK_COPPER_BULB_STEP = register("block.copper_bulb.step");
   public static final SoundEvent BLOCK_COPPER_BULB_TURN_OFF = register("block.copper_bulb.turn_off");
   public static final SoundEvent BLOCK_COPPER_BULB_TURN_ON = register("block.copper_bulb.turn_on");
   public static final SoundEvent BLOCK_COPPER_CHEST_CLOSE = register("block.copper_chest.close");
   public static final SoundEvent BLOCK_COPPER_CHEST_OPEN = register("block.copper_chest.open");
   public static final SoundEvent BLOCK_COPPER_CHEST_OXIDIZED_CLOSE = register("block.copper_chest_oxidized.close");
   public static final SoundEvent BLOCK_COPPER_CHEST_OXIDIZED_OPEN = register("block.copper_chest_oxidized.open");
   public static final SoundEvent BLOCK_COPPER_CHEST_WEATHERED_CLOSE = register("block.copper_chest_weathered.close");
   public static final SoundEvent BLOCK_COPPER_CHEST_WEATHERED_OPEN = register("block.copper_chest_weathered.open");
   public static final SoundEvent BLOCK_COPPER_DOOR_CLOSE = register("block.copper_door.close");
   public static final SoundEvent BLOCK_COPPER_DOOR_OPEN = register("block.copper_door.open");
   public static final SoundEvent BLOCK_COPPER_GOLEM_STATUE_BREAK = register("block.copper_golem_statue.break");
   public static final SoundEvent BLOCK_COPPER_GOLEM_STATUE_FALL = register("block.copper_golem_statue.fall");
   public static final SoundEvent BLOCK_COPPER_GOLEM_STATUE_HIT = register("block.copper_golem_statue.hit");
   public static final SoundEvent BLOCK_COPPER_GOLEM_STATUE_PLACE = register("block.copper_golem_statue.place");
   public static final SoundEvent BLOCK_COPPER_GOLEM_STATUE_STEP = register("block.copper_golem_statue.step");
   public static final SoundEvent BLOCK_COPPER_TRAPDOOR_CLOSE = register("block.copper_trapdoor.close");
   public static final SoundEvent BLOCK_COPPER_TRAPDOOR_OPEN = register("block.copper_trapdoor.open");
   public static final SoundEvent BLOCK_CRAFTER_CRAFT = register("block.crafter.craft");
   public static final SoundEvent BLOCK_CRAFTER_FAIL = register("block.crafter.fail");
   public static final SoundEvent BLOCK_HEAVY_CORE_BREAK = register("block.heavy_core.break");
   public static final SoundEvent BLOCK_HEAVY_CORE_FALL = register("block.heavy_core.fall");
   public static final SoundEvent BLOCK_HEAVY_CORE_HIT = register("block.heavy_core.hit");
   public static final SoundEvent BLOCK_HEAVY_CORE_PLACE = register("block.heavy_core.place");
   public static final SoundEvent BLOCK_HEAVY_CORE_STEP = register("block.heavy_core.step");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_ABOUT_TO_SPAWN_ITEM = register("block.trial_spawner.about_to_spawn_item");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_AMBIENT = register("block.trial_spawner.ambient");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_AMBIENT_OMINOUS = register("block.trial_spawner.ambient_ominous");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_BREAK = register("block.trial_spawner.break");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_CLOSE_SHUTTER = register("block.trial_spawner.close_shutter");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_DETECT_PLAYER = register("block.trial_spawner.detect_player");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_EJECT_ITEM = register("block.trial_spawner.eject_item");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_FALL = register("block.trial_spawner.fall");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_HIT = register("block.trial_spawner.hit");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_OMINOUS_ACTIVATE = register("block.trial_spawner.ominous_activate");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_OPEN_SHUTTER = register("block.trial_spawner.open_shutter");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_PLACE = register("block.trial_spawner.place");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_SPAWN_ITEM = register("block.trial_spawner.spawn_item");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_SPAWN_ITEM_BEGIN = register("block.trial_spawner.spawn_item_begin");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_SPAWN_MOB = register("block.trial_spawner.spawn_mob");
   public static final SoundEvent BLOCK_TRIAL_SPAWNER_STEP = register("block.trial_spawner.step");
   public static final SoundEvent BLOCK_VAULT_ACTIVATE = register("block.vault.activate");
   public static final SoundEvent BLOCK_VAULT_AMBIENT = register("block.vault.ambient");
   public static final SoundEvent BLOCK_VAULT_BREAK = register("block.vault.break");
   public static final SoundEvent BLOCK_VAULT_CLOSE_SHUTTER = register("block.vault.close_shutter");
   public static final SoundEvent BLOCK_VAULT_DEACTIVATE = register("block.vault.deactivate");
   public static final SoundEvent BLOCK_VAULT_EJECT_ITEM = register("block.vault.eject_item");
   public static final SoundEvent BLOCK_VAULT_FALL = register("block.vault.fall");
   public static final SoundEvent BLOCK_VAULT_HIT = register("block.vault.hit");
   public static final SoundEvent BLOCK_VAULT_INSERT_ITEM = register("block.vault.insert_item");
   public static final SoundEvent BLOCK_VAULT_INSERT_ITEM_FAIL = register("block.vault.insert_item_fail");
   public static final SoundEvent BLOCK_VAULT_OPEN_SHUTTER = register("block.vault.open_shutter");
   public static final SoundEvent BLOCK_VAULT_PLACE = register("block.vault.place");
   public static final SoundEvent BLOCK_VAULT_REJECT_REWARDED_PLAYER = register("block.vault.reject_rewarded_player");
   public static final SoundEvent BLOCK_VAULT_STEP = register("block.vault.step");
   public static final SoundEvent ENTITY_ARMADILLO_AMBIENT = register("entity.armadillo.ambient");
   public static final SoundEvent ENTITY_ARMADILLO_BRUSH = register("entity.armadillo.brush");
   public static final SoundEvent ENTITY_ARMADILLO_DEATH = register("entity.armadillo.death");
   public static final SoundEvent ENTITY_ARMADILLO_EAT = register("entity.armadillo.eat");
   public static final SoundEvent ENTITY_ARMADILLO_HURT = register("entity.armadillo.hurt");
   public static final SoundEvent ENTITY_ARMADILLO_HURT_REDUCED = register("entity.armadillo.hurt_reduced");
   public static final SoundEvent ENTITY_ARMADILLO_LAND = register("entity.armadillo.land");
   public static final SoundEvent ENTITY_ARMADILLO_PEEK = register("entity.armadillo.peek");
   public static final SoundEvent ENTITY_ARMADILLO_ROLL = register("entity.armadillo.roll");
   public static final SoundEvent ENTITY_ARMADILLO_SCUTE_DROP = register("entity.armadillo.scute_drop");
   public static final SoundEvent ENTITY_ARMADILLO_STEP = register("entity.armadillo.step");
   public static final SoundEvent ENTITY_ARMADILLO_UNROLL_FINISH = register("entity.armadillo.unroll_finish");
   public static final SoundEvent ENTITY_ARMADILLO_UNROLL_START = register("entity.armadillo.unroll_start");
   public static final SoundEvent ENTITY_BOGGED_AMBIENT = register("entity.bogged.ambient");
   public static final SoundEvent ENTITY_BOGGED_DEATH = register("entity.bogged.death");
   public static final SoundEvent ENTITY_BOGGED_HURT = register("entity.bogged.hurt");
   public static final SoundEvent ENTITY_BOGGED_SHEAR = register("entity.bogged.shear");
   public static final SoundEvent ENTITY_BOGGED_STEP = register("entity.bogged.step");
   public static final SoundEvent ENTITY_BREEZE_CHARGE = register("entity.breeze.charge");
   public static final SoundEvent ENTITY_BREEZE_DEATH = register("entity.breeze.death");
   public static final SoundEvent ENTITY_BREEZE_DEFLECT = register("entity.breeze.deflect");
   public static final SoundEvent ENTITY_BREEZE_HURT = register("entity.breeze.hurt");
   public static final SoundEvent ENTITY_BREEZE_IDLE_AIR = register("entity.breeze.idle_air");
   public static final SoundEvent ENTITY_BREEZE_IDLE_GROUND = register("entity.breeze.idle_ground");
   public static final SoundEvent ENTITY_BREEZE_INHALE = register("entity.breeze.inhale");
   public static final SoundEvent ENTITY_BREEZE_JUMP = register("entity.breeze.jump");
   public static final SoundEvent ENTITY_BREEZE_LAND = register("entity.breeze.land");
   public static final SoundEvent ENTITY_BREEZE_SHOOT = register("entity.breeze.shoot");
   public static final SoundEvent ENTITY_BREEZE_SLIDE = register("entity.breeze.slide");
   public static final SoundEvent ENTITY_BREEZE_WHIRL = register("entity.breeze.whirl");
   public static final SoundEvent ENTITY_BREEZE_WIND_BURST = register("entity.breeze.wind_burst");
   public static final SoundEvent ENTITY_CAMEL_HUSK_AMBIENT = register("entity.camel_husk.ambient");
   public static final SoundEvent ENTITY_CAMEL_HUSK_DASH = register("entity.camel_husk.dash");
   public static final SoundEvent ENTITY_CAMEL_HUSK_DASH_READY = register("entity.camel_husk.dash_ready");
   public static final SoundEvent ENTITY_CAMEL_HUSK_DEATH = register("entity.camel_husk.death");
   public static final SoundEvent ENTITY_CAMEL_HUSK_EAT = register("entity.camel_husk.eat");
   public static final SoundEvent ENTITY_CAMEL_HUSK_HURT = register("entity.camel_husk.hurt");
   public static final SoundEvent ENTITY_CAMEL_HUSK_SADDLE = register("entity.camel_husk.saddle");
   public static final SoundEvent ENTITY_CAMEL_HUSK_SIT = register("entity.camel_husk.sit");
   public static final SoundEvent ENTITY_CAMEL_HUSK_STAND = register("entity.camel_husk.stand");
   public static final SoundEvent ENTITY_CAMEL_HUSK_STEP = register("entity.camel_husk.step");
   public static final SoundEvent ENTITY_CAMEL_HUSK_STEP_SAND = register("entity.camel_husk.step_sand");
   public static final SoundEvent ENTITY_COPPER_GOLEM_DEATH = register("entity.copper_golem.death");
   public static final SoundEvent ENTITY_COPPER_GOLEM_HURT = register("entity.copper_golem.hurt");
   public static final SoundEvent ENTITY_COPPER_GOLEM_ITEM_DROP = register("entity.copper_golem.item_drop");
   public static final SoundEvent ENTITY_COPPER_GOLEM_ITEM_NO_DROP = register("entity.copper_golem.item_no_drop");
   public static final SoundEvent ENTITY_COPPER_GOLEM_NO_ITEM_GET = register("entity.copper_golem.no_item_get");
   public static final SoundEvent ENTITY_COPPER_GOLEM_NO_ITEM_NO_GET = register("entity.copper_golem.no_item_no_get");
   public static final SoundEvent ENTITY_COPPER_GOLEM_SHEAR = register("entity.copper_golem.shear");
   public static final SoundEvent ENTITY_COPPER_GOLEM_SPAWN = register("entity.copper_golem.spawn");
   public static final SoundEvent ENTITY_COPPER_GOLEM_SPIN = register("entity.copper_golem.spin");
   public static final SoundEvent ENTITY_COPPER_GOLEM_STEP = register("entity.copper_golem.step");
   public static final SoundEvent ENTITY_COPPER_GOLEM_BECOME_STATUE = register("entity.copper_golem_become_statue");
   public static final SoundEvent ENTITY_COPPER_GOLEM_OXIDIZED_DEATH = register("entity.copper_golem_oxidized.death");
   public static final SoundEvent ENTITY_COPPER_GOLEM_OXIDIZED_HURT = register("entity.copper_golem_oxidized.hurt");
   public static final SoundEvent ENTITY_COPPER_GOLEM_OXIDIZED_SPIN = register("entity.copper_golem_oxidized.spin");
   public static final SoundEvent ENTITY_COPPER_GOLEM_OXIDIZED_STEP = register("entity.copper_golem_oxidized.step");
   public static final SoundEvent ENTITY_COPPER_GOLEM_WEATHERED_DEATH = register("entity.copper_golem_weathered.death");
   public static final SoundEvent ENTITY_COPPER_GOLEM_WEATHERED_HURT = register("entity.copper_golem_weathered.hurt");
   public static final SoundEvent ENTITY_COPPER_GOLEM_WEATHERED_SPIN = register("entity.copper_golem_weathered.spin");
   public static final SoundEvent ENTITY_COPPER_GOLEM_WEATHERED_STEP = register("entity.copper_golem_weathered.step");
   public static final SoundEvent ENTITY_PARCHED_AMBIENT = register("entity.parched.ambient");
   public static final SoundEvent ENTITY_PARCHED_DEATH = register("entity.parched.death");
   public static final SoundEvent ENTITY_PARCHED_HURT = register("entity.parched.hurt");
   public static final SoundEvent ENTITY_PARCHED_STEP = register("entity.parched.step");
   public static final SoundEvent ENTITY_WIND_CHARGE_THROW = register("entity.wind_charge.throw");
   public static final SoundEvent ENTITY_WIND_CHARGE_WIND_BURST = register("entity.wind_charge.wind_burst");
   public static final SoundEvent ITEM_ARMOR_EQUIP_WOLF = register("item.armor.equip_wolf");
   public static final SoundEvent ITEM_ARMOR_UNEQUIP_WOLF = register("item.armor.unequip_wolf");
   public static final SoundEvent ITEM_MACE_SMASH_AIR = register("item.mace.smash_air");
   public static final SoundEvent ITEM_MACE_SMASH_GROUND = register("item.mace.smash_ground");
   public static final SoundEvent ITEM_MACE_SMASH_GROUND_HEAVY = register("item.mace.smash_ground_heavy");
   public static final SoundEvent ITEM_WOLF_ARMOR_BREAK = register("item.wolf_armor.break");
   public static final SoundEvent ITEM_WOLF_ARMOR_CRACK = register("item.wolf_armor.crack");
   public static final SoundEvent ITEM_WOLF_ARMOR_DAMAGE = register("item.wolf_armor.damage");
   public static final SoundEvent ITEM_WOLF_ARMOR_REPAIR = register("item.wolf_armor.repair");

   private BackportSounds() {
   }

   private static SoundEvent register(String name) {
      return Registry.register(BuiltInRegistries.SOUND_EVENT, Backport.id(name), SoundEvent.createVariableRangeEvent(Backport.id(name)));
   }

   public static void init() {
   }
}
